### ISSUE TITLE
Manual bootstrap instructions lack AWS creds

### ISSUE THREAD

**Issue by mook-as** [colstrom/cloudstrap#10]
If you _don't_ disable human intervention, at the end cloudstrap prints out instructions for setting up the node:

```
When you are ready to proceed, the following command will do the rest:

ssh -l ubuntu -i …ssh_key 192.0.2.1 bootstrap
```

This does not tell you that you need to get your AWS access + secret keys there, somehow. Cloudstrap normally does this via environment variables, but as written there won't be any when `bootstrap` is run.

**Comment by colstrom** [comment]
Resolved in 3dc70d05738936bd0b4a61974ad3887163e94945
