### ISSUE TITLE
cloudstrap-dns doesn't work with zone != domain

### ISSUE THREAD

**Issue by mook-as** [colstrom/cloudstrap#15]
See also #13, #14 
If I want to deploy my cluster such that `HCPDomainName` isn't my Route53 zone's domain name, things break.  For example, my hosted zone could be `mook-as.example.com`, but my `HCPDomainName` setting could be `hcp.aws.mook-as.example.com`. (The end result being a host named `identity.hcp.aws.mook-as.example.com`)

**Comment by colstrom** [comment]
Resolved in eec8060 (0.37.0)
