### ISSUE TITLE
Multi AZ support. 

### ISSUE THREAD

**Issue by prabalsharma** [colstrom/cloudstrap#21]
3 AZ
AWS.AvailabilityZones         = us-west-2a,us-west-2b,us-west-2c
AWS.PublicSubnetIDsAndAZ      = <<subnet1:az1, subnet2:az2>>
AWS.PrivateSubnetIDsAndAZ     = <<subnet1:az1, subnet2:az2>>

**Comment by colstrom** [comment]
Multi-AZ support is implemented in `0.40.0`. Enjoy!
