### ISSUE TITLE
please add these to bootstrap.properties

### ISSUE THREAD

**Issue by prabalsharma** [colstrom/cloudstrap#23]
Docker.Username
Docker.Password
AWS.AccessKey
AWS.SecretKey

**Comment by prabalsharma** [comment]
Docker stuff required of HCE install
key stuff is required for other tools dependent on sample_bootstrap.properties file

**Comment by colstrom** [comment]
Credentials don't belong in cleartext configs.

If you enable `BOOTSTRAP_WITHOUT_HUMAN_OVERSIGHT`, the AWS credentials are inserted into the environment when HCP's bootstrap is launched.

Regarding docker credentials, this could be handled similarly, if there's an environment variable HCP's bootstrap will consume.

That said, Cloudstrap will pass any parameters in your `bootstrap.properties` that it does not understand along without modification.

**Comment by colstrom** [comment]
Confirmed that hcp-bootstrap does not _currently_ support configuring this via environment.
