### ISSUE TITLE
Add support for "number of zones" config entry

### ISSUE THREAD

**Issue by jandubois** [colstrom/cloudstrap#26]
Creating a cluster on `us-east-1` populates `bootstrap.properties` with 5 zones (and subnets). Bootstrap only supports 1 or 3.

I would like to specify the desired number of zones in `config.yaml` and not edit `bootstrap.properties` manually.

**Comment by colstrom** [comment]
This is a deficiency in how bootstrap handles AZs. Having more availability zones than it can use should not be a failure condition. Cloudstrap could try to be clever about this, only a subset of availability zones to bootstrap, but that would be masking the underlying issue.

**Comment by colstrom** [comment]
This is resolved in 7baa244c9570c4b4304e193504c3527507684be7 (`0.47.2`). You can set `maximum_availability_zones` in your configuration. It defaults to `3` so is unlikely to require modification.

As a companion feature, `0.47.5` introduced a `minimum_availability_zones` setting (defaulting to `1`). If there are insufficient AZs to meet the minimum requested, it will reuse one or more of them. This should allow HA deployments in `us-west-1` and other regions with fewer than 3 AZs.
