### ISSUE TITLE
Default node type should be m4.2xlarge

### ISSUE THREAD

**Issue by HartS** [colstrom/cloudstrap#35]
We will not be able to deploy HA HCF out of the box if the nodes are m4.xlarge

**Comment by colstrom** [comment]
This can be set in `config.yaml` with the `node_instance_type` key.

Given that `cloudstrap` does not deploy HCF, I'm not sure provisioning larger instances by default is the Right Thing to do.

**Comment by colstrom** [comment]
Merged #37
