### ISSUE TITLE
Add ability to specify smaller/explicit CIDR ranges

### ISSUE THREAD

**Issue by troytop** [colstrom/cloudstrap#40]
I tried specifying these CIDR ranges explicitly:

vpc_cidr_block: 10.2.3.0/27
public_cidr_block: 10.2.3.0/28
private_cidr_block: 10.2.3.16/28

Didn't work. Gave me this error:

$ cloudstrap
/home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.7.11/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The CIDR '10.2.0.0/24' is invalid. (Aws::EC2::Errors::InvalidSubnetRange)
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.7.11/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.7.11/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.7.11/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.7.11/lib/seahorse/client/request.rb:70:in `send_request'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.7.11/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cloudstrap-0.48.2.pre/lib/cloudstrap/amazon/support/rate_limit_handler.rb:30:in `call'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cloudstrap-0.48.2.pre/lib/cloudstrap/amazon/support/rate_limit_handler.rb:30:in `block in call_api'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/retries-0.0.5/lib/retries.rb:46:in `with_retries'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cloudstrap-0.48.2.pre/lib/cloudstrap/amazon/support/rate_limit_handler.rb:21:in `call_api'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/call_with.rb:76:in `call_with'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cloudstrap-0.48.2.pre/lib/cloudstrap/amazon/ec2.rb:323:in `create_subnet'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/call_with.rb:76:in `call_with'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cloudstrap-0.48.2.pre/lib/cloudstrap/agent.rb:232:in `block in public_subnets'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cloudstrap-0.48.2.pre/lib/cloudstrap/agent.rb:230:in `each'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cloudstrap-0.48.2.pre/lib/cloudstrap/agent.rb:230:in `map'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cloudstrap-0.48.2.pre/lib/cloudstrap/agent.rb:230:in `public_subnets'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/call_with.rb:76:in `call_with'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cloudstrap-0.48.2.pre/lib/cloudstrap/agent.rb:168:in `public_subnet'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/call_with.rb:76:in `call_with'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cloudstrap-0.48.2.pre/lib/cloudstrap/agent.rb:89:in `create_nat_gateway'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/call_with.rb:76:in `call_with'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cloudstrap-0.48.2.pre/lib/cloudstrap/agent.rb:96:in `block (2 levels) in nat_gateway'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/moneta-0.8.1/lib/moneta/mixins.rb:165:in `fetch'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cloudstrap-0.48.2.pre/lib/cloudstrap/agent.rb:95:in `block in nat_gateway'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cloudstrap-0.48.2.pre/lib/cloudstrap/agent.rb:94:in `fetch'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cloudstrap-0.48.2.pre/lib/cloudstrap/agent.rb:94:in `nat_gateway'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/call_with.rb:76:in `call_with'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cloudstrap-0.48.2.pre/bin/cloudstrap:65:in `<top (required)>'
	from /home/troyt/.rbenv/versions/2.4.0/bin/cloudstrap:22:in `load'
	from /home/troyt/.rbenv/versions/2.4.0/bin/cloudstrap:22:in `<main>'

**Comment by colstrom** [comment]
This is available in `0.49.1`+. Thanks for the suggestion!
