### ISSUE TITLE
Deprecation warnings in cloudstrap-cache output

### ISSUE THREAD

**Issue by troytop** [colstrom/cloudstrap#41]
`$ cloudstrap-cache
/home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/necromancer-0.3.0/lib/necromancer/conversion_target.rb:69: warning: constant ::Fixnum is deprecated
/home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/necromancer-0.3.0/lib/necromancer/conversion_target.rb:69: warning: constant ::Bignum is deprecated
/home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/necromancer-0.3.0/lib/necromancer/conversion_target.rb:69: warning: constant ::Fixnum is deprecated
/home/troyt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/necromancer-0.3.0/lib/necromancer/conversion_target.rb:69: warning: constant ::Bignum is deprecated
`

... followed by expected output.

**Comment by colstrom** [comment]
Fixed in `0.48.15.pre`
