### ISSUE TITLE
create vpc with 'DNS hostnames: yes'

### ISSUE THREAD

**Issue by troytop** [colstrom/cloudstrap#8]
This is required by some services.

**Comment by colstrom** [comment]
Implemented in 1489c4148476315acdda01d7b09b4d8502fd3471. It will also update existing VPCs in-place, so no teardowns required.

Released in in `0.30.1`

**Comment by mook-as** [comment]
This doesn't seem to work; it turns on _DNS resolution_, not _DNS hostnames_.
